services:

  db:
    image: postgres:14.5
    restart: always
    container_name: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
#    command: ["./wait-for-it.sh", "db:5432", "--",
#              "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
    command: python3 /code/myshop/manage.py runserver 0.0.0.0:8000
    restart: always
    container_name: myshop
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=myshop.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"
